var skills = {
		temp:"circle",
		skillsClassify:[
		{
			skillLanguage:"HTML",
			percent:"80%",
			skillTooltip:[
				"熟练掌握各类语义化标签",
				"熟悉新增的表单控件，表单验证以及相关属性",
				"HTML5新增选择器，JSON新方法，历史管理",
				"视频音频",
				"canvas画图"
			]
		},
		{
			skillLanguage:"CSS",
			percent:"70%",
			skillTooltip:[
				"熟练运用css及css3新属性",
				"熟悉定位、浏览器兼容性",
				"熟悉CSS3结构选择器、伪类选择器、伪元素",
				"CSS3圆角盒子阴影文字阴影动画等有实际案例经验"
			]
		},
		{
			skillLanguage:"javascript",
			percent:"75%",
			skillTooltip:[
				"了解数据类型、作用域闭包等语言特性",
				"掌握定时器、数组字符串及递归、数组去重等",
				"深入使用DOM、BOM、EVENT，能完成各类组件开发",
				"掌握JS的数据调用、ajax实现机制、各类接口调用",
				"掌握面向对象编程，对封装、继承、多态等均有了解",
				"了解正则表达式，熟悉JS兼容性、JS性能提升"
			]
		},
		{
			skillLanguage:"jQuery",
			percent:"60%",
			skillTooltip:[
				"熟练使用JQ进行页面开发，有实际开发经验",
				"移动端响应式"
			]
		},
		{
			skillLanguage:"Ajax",
			percent:"50%",
			skillTooltip:[
				"能熟练使用接口进行数据交互，以及数据的处理",
				"能运用JQ提供的Ajax方法进行交互"
			]
		},
		{
			skillLanguage:"框架及工具",
			percent:"65%",
			skillTooltip:[
				"能够熟练的使用git命令进行版本控制的开发",
				"了解一些react的使用方法及jsx语法",
				"熟悉一些常用的es6的语法",
				"利用react和bs做了一个小demo"
			]
		}
		]
}

var projects = [
			{
				projectName:"PC端及移动端2048",
				projectWebsite:"2048游戏/PC端/index.html",
				projectExplain:"利用HTML、CSS及JavaScript基本知识,以及jQuery基本用法开发一款适合PC端及移动端玩的2048,主要是键盘事件以及触摸事件的运用以及动画等的使用",
				projectImg:"resume/img/2048.png"
			},
			{
				projectName:"静态电商网站",
				projectWebsite:"电商网站/index.html",
				projectExplain:"通过运用html及css的相关知识进行开发的一套静态电商网站。其中用到了布局、定位、浮动、兼容等的知识。",
				projectImg:"resume/img/电商网站.png"
			},
			{
				projectName:"移动端相册",
				projectWebsite:"移动端相册/index.html",
				projectExplain:"利用原生js进行开发移动端相册，使用到了rem进行适配，以及一些节点的操作。",
				projectImg:"resume/img/移动端相册.png"
			},
			{
				projectName:"移动端音乐播放器",
				projectWebsite:"移动端音乐播放器/移动端音乐播放器.html",
				projectExplain:"利用到了Html5中的音频标签及相关的媒体元素，以及运用到了rem进行适配，从而实现一个简易的音乐播放器。",
				projectImg:"resume/img/移动端音乐播放器.png"
			}
		] 
